# Generated by Django 2.2.1 on 2019-05-09 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveymaker', '0002_auto_20190509_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='surveymaker.MCQuestion'),
        ),
        migrations.AlterField(
            model_name='mcquestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveymaker.Survey'),
        ),
    ]
